hmcts/rpa-coh-continuous-online-resolution

src/aat/java/uk/gov/hmcts/reform/coh/functional/bdd/runner/ContinuousOnlineHearingTests.java, src/aat/java/uk/gov/hmcts/reform/coh/functional/bdd/steps/AnswerSteps.java, src/aat/java/uk/gov/hmcts/reform/coh/functional/bdd/steps/ApiSteps.java, src/aat/java/uk/gov/hmcts/reform/coh/functional/bdd/utils/TestTrustManager.java, src/aat/resources/application.yaml, src/aat/resources/cucumber/online-hearing.feature, src/main/java/uk/gov/hmcts/reform/coh/domain/Question.java, src/main/java/uk/gov/hmcts/reform/coh/repository/OnlineHearingRepository.java, src/main/java/uk/gov/hmcts/reform/coh/service/AnswerService.java, src/main/java/uk/gov/hmcts/reform/coh/service/OnlineHearingService.java, src/main/java/uk/gov/hmcts/reform/coh/service/QuestionService.java, src/test/java/uk/gov/hmcts/reform/coh/service/AnswerServiceTest.java, src/test/java/uk/gov/hmcts/reform/coh/service/OnlineHearingServiceTest.java, src/test/java/uk/gov/hmcts/reform/coh/service/QuestionServiceTest.java
This is basically a hack due to the integration test environment not having correct security certificates. The changes are configuring the test to basically trust any certificate that's being presented
=> Allow all certificates

src/aat/java/uk/gov/hmcts/reform/coh/functional/bdd/steps/AnswerSteps.java, src/aat/java/uk/gov/hmcts/reform/coh/functional/bdd/steps/ApiSteps.java, src/aat/java/uk/gov/hmcts/reform/coh/functional/bdd/steps/QuestionSteps.java
In addition to these changes. I have updated the test harness jurisdiction url rows in the azure db
=> Fix jenkins test

src/aat/java/uk/gov/hmcts/reform/coh/functional/bdd/steps/AnswerSteps.java, src/aat/java/uk/gov/hmcts/reform/coh/functional/bdd/steps/QuestionSteps.java, src/aat/resources/json/create_online_hearing.json, src/main/java/uk/gov/hmcts/reform/coh/repository/OnlineHearingRepository.java, src/main/java/uk/gov/hmcts/reform/coh/service/OnlineHearingService.java, src/test/java/uk/gov/hmcts/reform/coh/service/OnlineHearingServiceTest.java, src/test/resources/json/create_online_hearing.json
=> replace all occurrences of externalRef with caseId

src/main/java/uk/gov/hmcts/reform/coh/controller/DecisionController.java, src/main/java/uk/gov/hmcts/reform/coh/controller/decision/DecisionResponse.java, src/main/java/uk/gov/hmcts/reform/coh/controller/decision/DecisionResponseMapper.java, src/main/java/uk/gov/hmcts/reform/coh/repository/DecisionStateHistoryRepository.java, src/main/java/uk/gov/hmcts/reform/coh/service/DecisionService.java, src/main/java/uk/gov/hmcts/reform/coh/service/DecisionStateHistoryService.java, src/test/java/uk/gov/hmcts/reform/coh/controller/DecisionControllerTest.java, src/test/java/uk/gov/hmcts/reform/coh/controller/decision/DecisionResponseMapperTest.java, src/test/java/uk/gov/hmcts/reform/coh/service/DecisionServiceTest.java
1. Fix the expiry date to be 7 days in the future
2. Fixed the endpoint so that the decision id is not required
3. Added the state date time to the decision GET response
=> Add timestamp to get

src/aat/resources/cucumber/questionrounds.feature, src/aat/resources/cucumber/questions.feature, src/aat/resources/json/question_round/issue_question_round.json, src/main/java/uk/gov/hmcts/reform/coh/controller/QuestionController.java, src/main/java/uk/gov/hmcts/reform/coh/domain/QuestionState.java, src/main/java/uk/gov/hmcts/reform/coh/service/QuestionRoundService.java, src/main/java/uk/gov/hmcts/reform/coh/service/QuestionService.java, src/main/java/uk/gov/hmcts/reform/coh/states/QuestionStates.java, src/main/resources/db/changelog/sql/question_states.sql, src/test/java/uk/gov/hmcts/reform/coh/controller/QuestionControllerTest.java, src/test/java/uk/gov/hmcts/reform/coh/service/DecisionServiceTest.java, src/test/java/uk/gov/hmcts/reform/coh/service/QuestionRoundServiceTest.java, src/test/java/uk/gov/hmcts/reform/coh/service/QuestionServiceTest.java, src/test/resources/json/question_round/issue_question_round.json
All thos hard-coded values have now been moved to an Enum
=> Refactor hardcoded question state

src/aat/java/uk/gov/hmcts/reform/coh/functional/bdd/steps/DecisionSteps.java, src/aat/java/uk/gov/hmcts/reform/coh/functional/bdd/steps/QuestionSteps.java, src/aat/resources/cucumber/questions.feature, src/main/java/uk/gov/hmcts/reform/coh/controller/QuestionController.java, src/test/java/uk/gov/hmcts/reform/coh/controller/QuestionControllerTest.java
This is for story: 
https://tools.hmcts.net/jira/browse/COH-90
=> Coh 90 delete a question

src/aat/resources/cucumber/questionrounds.feature, src/main/java/uk/gov/hmcts/reform/coh/controller/QuestionRoundController.java, src/main/java/uk/gov/hmcts/reform/coh/service/QuestionRoundService.java, src/test/java/uk/gov/hmcts/reform/coh/service/QuestionRoundServiceTest.java
Also tidied up the QR unit tests
=> Fix 500 server error when re-issuing a question round

build.gradle, src/aat/java/uk/gov/hmcts/reform/coh/functional/bdd/steps/QuestionSteps.java, src/main/java/uk/gov/hmcts/reform/coh/controller/AnswerController.java, src/main/java/uk/gov/hmcts/reform/coh/controller/DecisionController.java, src/main/java/uk/gov/hmcts/reform/coh/controller/OnlineHearingController.java, src/main/java/uk/gov/hmcts/reform/coh/controller/QuestionController.java, src/main/java/uk/gov/hmcts/reform/coh/controller/question/UpdateQuestionRequest.java, src/main/java/uk/gov/hmcts/reform/coh/controller/question/UpdateQuestionRequestMapper.java, src/main/java/uk/gov/hmcts/reform/coh/controller/validators/DecisionRequestValidator.java, src/main/java/uk/gov/hmcts/reform/coh/controller/validators/QuestionValidator.java, src/main/java/uk/gov/hmcts/reform/coh/controller/validators/Validation.java, src/main/java/uk/gov/hmcts/reform/coh/controller/validators/Validator.java, src/main/java/uk/gov/hmcts/reform/coh/controller/validators/ValidatorUtils.java, src/test/java/uk/gov/hmcts/reform/coh/controller/QuestionControllerTest.java, src/test/java/uk/gov/hmcts/reform/coh/controller/validators/DecisionRequestValidatorTest.java, src/test/java/uk/gov/hmcts/reform/coh/controller/validators/QuestionRequestValidatorTest.java, src/test/java/uk/gov/hmcts/reform/coh/controller/validators/ValidationUtilsTest.java
This is a refactor of the validator for request. Basically remove that copy paste validation executor.
=> Refactor validators

src/aat/resources/cucumber/decisions.feature, src/main/java/uk/gov/hmcts/reform/coh/controller/DecisionController.java, src/main/java/uk/gov/hmcts/reform/coh/task/DecisionIssuedTask.java, src/test/java/uk/gov/hmcts/reform/coh/controller/DecisionControllerTest.java, src/test/java/uk/gov/hmcts/reform/coh/task/DecisionIssuedTaskTest.java
https://tools.hmcts.net/jira/browse/COH-108?workflowName=RPA+Complex+Workflow+v2&stepId=1
Online hearing state updated when decision issued
=> COH-108-Set-Decision-State-For-Online-Hearing

src/main/java/uk/gov/hmcts/reform/coh/task/ContinuousOnlineResolutionTaskFactory.java, src/test/java/uk/gov/hmcts/reform/coh/task/ContinuousOnlineResolutionTaskFactoryTest.java
=> Add factory for tasks

src/aat/java/uk/gov/hmcts/reform/coh/functional/bdd/steps/DeadlineSteps.java, src/aat/java/uk/gov/hmcts/reform/coh/functional/bdd/steps/JsonUtils.java, src/aat/resources/application.yaml, src/aat/resources/cucumber/deadline-extension.feature, src/main/java/uk/gov/hmcts/reform/coh/controller/DeadlineController.java, src/main/java/uk/gov/hmcts/reform/coh/service/QuestionService.java, src/main/java/uk/gov/hmcts/reform/coh/service/QuestionStateService.java, src/main/java/uk/gov/hmcts/reform/coh/service/exceptions/NoQuestionsAsked.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/coh/controller/DeadlineControllerTest.java, src/test/java/uk/gov/hmcts/reform/coh/service/QuestionServiceTest.java, src/test/java/uk/gov/hmcts/reform/coh/service/QuestionStateServiceTest.java
https://tools.hmcts.net/jira/browse/COH-112
Appellant can request deadline extension for the issued questions.
=> Deadline extension endpoint

src/aat/java/uk/gov/hmcts/reform/coh/functional/bdd/steps/QuestionSteps.java, src/aat/resources/cucumber/deadline-extension.feature
https://tools.hmcts.net/jira/browse/COH-112
=> Add cucumber step for checking number of events in questions history

src/aat/java/uk/gov/hmcts/reform/coh/functional/bdd/steps/AnswerSteps.java, src/main/java/uk/gov/hmcts/reform/coh/controller/OnlineHearingController.java, src/main/java/uk/gov/hmcts/reform/coh/domain/OnlineHearingStateHistory.java, src/main/java/uk/gov/hmcts/reform/coh/domain/QuestionStateHistory.java, src/main/resources/db/changelog/db.changelog-diff-20180804-1126.yaml, src/main/resources/db/changelog/db.changelog-master.yaml
Certain entities can re-enter previously used states. This PR will remove compound key restrictions.
=> Fix compound keys

src/aat/resources/cucumber/notifications.feature, src/test/java/uk/gov/hmcts/reform/coh/schedule/notifiers/StandardTransformerTest.java
https://tools.hmcts.net/jira/browse/COH-96
=> COH-96: Add tests for sending notification about denied deadline extension

src/main/java/uk/gov/hmcts/reform/coh/controller/answer/AnswerRequest.java, src/main/java/uk/gov/hmcts/reform/coh/controller/decision/DecisionRequest.java, src/main/java/uk/gov/hmcts/reform/coh/controller/decision/UpdateDecisionRequest.java, src/main/java/uk/gov/hmcts/reform/coh/controller/decisionreplies/DecisionReplyRequest.java, src/main/java/uk/gov/hmcts/reform/coh/controller/events/EventRegistrationRequest.java, src/main/java/uk/gov/hmcts/reform/coh/controller/events/ResetSessionEventRequest.java, src/main/java/uk/gov/hmcts/reform/coh/controller/onlinehearing/OnlineHearingRequest.java, src/main/java/uk/gov/hmcts/reform/coh/controller/onlinehearing/UpdateOnlineHearingRequest.java, src/main/java/uk/gov/hmcts/reform/coh/controller/question/QuestionRequest.java, src/main/java/uk/gov/hmcts/reform/coh/controller/question/UpdateQuestionRequest.java, src/main/java/uk/gov/hmcts/reform/coh/controller/questionrounds/QuestionRoundRequest.java
All request models have been annotated to include better description for swagger generated docs.
=> Update swagger apidocs

src/aat/java/uk/gov/hmcts/reform/coh/functional/bdd/steps/ApiSteps.java, src/aat/java/uk/gov/hmcts/reform/coh/functional/bdd/steps/BaseSteps.java
Remove duplicate HTTP clients. Use RestTemplate from Spring for consistency
=> Cucumber test refactoring

src/main/java/uk/gov/hmcts/reform/coh/controller/AnswerController.java, src/main/java/uk/gov/hmcts/reform/coh/controller/DecisionController.java, src/main/java/uk/gov/hmcts/reform/coh/controller/OnlineHearingController.java, src/main/java/uk/gov/hmcts/reform/coh/controller/QuestionController.java
Use CohUriBuilder to create the URI when returning the uri to the newly created entity
=> Use CohUriBuilder to create the URI 

src/aat/java/uk/gov/hmcts/reform/coh/functional/bdd/steps/DeadlineSteps.java, src/main/java/uk/gov/hmcts/reform/coh/controller/DecisionController.java, src/main/java/uk/gov/hmcts/reform/coh/service/QuestionRoundService.java, src/main/java/uk/gov/hmcts/reform/coh/service/QuestionService.java, src/main/java/uk/gov/hmcts/reform/coh/service/utils/ExpiryCalendar.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/coh/service/DecisionServiceTest.java, src/test/java/uk/gov/hmcts/reform/coh/service/utils/ExpiryCalendarTest.java, src/test/resources/application-local.yaml
AAT has it's own application.yaml which must have the same expirydeadline value as the main application.yaml.
=> Expiry calendar holds expiry days variable. Set using app config

src/aat/java/uk/gov/hmcts/reform/coh/functional/bdd/steps/QuestionSteps.java, src/aat/resources/cucumber/questions.feature, src/main/java/uk/gov/hmcts/reform/coh/controller/QuestionController.java, src/main/java/uk/gov/hmcts/reform/coh/controller/question/CreateQuestionResponse.java, src/main/java/uk/gov/hmcts/reform/coh/controller/question/QuestionRequest.java, src/main/java/uk/gov/hmcts/reform/coh/controller/question/UpdateQuestionRequestMapper.java, src/main/java/uk/gov/hmcts/reform/coh/domain/AnswerState.java, src/test/java/uk/gov/hmcts/reform/coh/controller/QuestionControllerTest.java, src/test/java/uk/gov/hmcts/reform/coh/util/AnswerEntityUtils.java, src/test/java/uk/gov/hmcts/reform/coh/util/AnswerStateUtils.java
First cut of updates to linked questions with unit and cucumber tests
=> Link Questions Across Rounds - PUT

src/main/java/uk/gov/hmcts/reform/coh/controller/AnswerController.java, src/test/java/uk/gov/hmcts/reform/coh/controller/AnswerControllerTest.java
Fixes bug where question that got deadline extended could not been
answered.
=> Extend list of answerable states for question

src/aat/resources/cucumber/deadline-extension.feature, src/main/java/uk/gov/hmcts/reform/coh/controller/DeadlineController.java, src/test/java/uk/gov/hmcts/reform/coh/controller/DeadlineControllerTest.java
JIRA: [COH-169](https://tools.hmcts.net/jira/browse/COH-169)
=> Return 424 when all questions were denied extension

src/main/java/uk/gov/hmcts/reform/coh/controller/OnlineHearingController.java, src/main/java/uk/gov/hmcts/reform/coh/domain/OnlineHearing.java, src/main/resources/db/changelog/db.changelog-diff-20181004-0933.yaml, src/main/resources/db/changelog/db.changelog-master.yaml
https://tools.hmcts.net/jira/browse/COH-177
=> Add uniqueness constraint on case_id in online hearing

build.gradle
=> Upgrade tomcat-embed-core dependency

build.gradle, infrastructure/main.tf, infrastructure/test_config.tf, src/aat/java/uk/gov/hmcts/reform/coh/functional/bdd/steps/EventSteps.java, src/aat/resources/application.yaml, src/aat/resources/cucumber/notifications.feature, src/main/java/uk/gov/hmcts/reform/coh/config/ServiceTokenGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/coh/schedule/notifiers/BasicJsonNotificationForwarder.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/coh/schedule/notifiers/BasicJsonNotificationForwarderTest.java
https://tools.hmcts.net/jira/browse/COH-181
=> [PREVIEW] Provide valid S2S tokens when sending notification

src/main/java/uk/gov/hmcts/reform/coh/controller/AnswerController.java, src/main/java/uk/gov/hmcts/reform/coh/controller/DecisionController.java, src/main/java/uk/gov/hmcts/reform/coh/controller/EventQueueController.java, src/main/java/uk/gov/hmcts/reform/coh/exception/GenericException.java, src/main/java/uk/gov/hmcts/reform/coh/schedule/notifiers/BasicJsonNotificationForwarder.java, src/main/java/uk/gov/hmcts/reform/coh/schedule/notifiers/EventNotifierJob.java, src/main/java/uk/gov/hmcts/reform/coh/schedule/trigger/AbstractQuestionRoundEventTrigger.java, src/main/java/uk/gov/hmcts/reform/coh/schedule/trigger/EventTriggerJob.java, src/main/java/uk/gov/hmcts/reform/coh/schedule/trigger/QuestionRoundDeadlineElapsed.java, src/main/java/uk/gov/hmcts/reform/coh/schedule/trigger/QuestionRoundReminder.java, src/main/java/uk/gov/hmcts/reform/coh/service/SessionEventService.java, src/main/java/uk/gov/hmcts/reform/coh/task/DecisionIssuedTask.java
This should help clearing AppInsight logs from `InvalidExceptionImplementation`.
=> [PREVIEW] Fix implementation of error logging

infrastructure/main.tf, infrastructure/variables.tf
The appender got deprecated with java-logging v4.0.0.
=> Remove JSON log appender

src/aat/java/uk/gov/hmcts/reform/coh/functional/bdd/steps/BaseSteps.java
Old endpoint had API changed so new endpoint was required.
=> Update user-finding endpoint of IdAM

build.gradle
Fixes [CVE-2018-15756](https://nvd.nist.gov/vuln/detail/CVE-2018-15756).
=> Upgrade Spring Boot to 2.0.8.RELEASE

Jenkinsfile_CNP, Jenkinsfile_parameterized, infrastructure/main.tf
Necessary for having this injected into environment by Jenkins.
=> Store S2S secret in local vault

src/main/java/uk/gov/hmcts/reform/coh/controller/AnswerController.java, src/test/java/uk/gov/hmcts/reform/coh/controller/AnswerControllerTest.java, src/test/java/uk/gov/hmcts/reform/coh/controller/LoggingAnswerUpdateErrorsTest.java
https://tools.hmcts.net/jira/browse/SSCS-5077
=> Log answer update errors

src/main/java/uk/gov/hmcts/reform/coh/controller/question/UpdateQuestionRequestMapper.java, src/test/java/uk/gov/hmcts/reform/coh/controller/question/UpdateQuestionRequestMapperTest.java
[RIUI-1445](https://tools.hmcts.net/jira/browse/RIUI-1445)
=> Map owner id from request to entity

src/test/java/uk/gov/hmcts/reform/coh/controller/question/UpdateQuestionRequestMapperTest.java
[COH-192](https://tools.hmcts.net/jira/browse/COH-192)
=> Add test cases for UpdateQuestionRequestMapper

src/main/java/uk/gov/hmcts/reform/coh/controller/question/UpdateQuestionRequestMapper.java, src/test/java/uk/gov/hmcts/reform/coh/controller/question/UpdateQuestionRequestMapperTest.java
Question round from request was mapped to question ordinal in entity.
=> Fix mapping question round

src/main/resources/application.yaml
Panel Members will access COH from JUI and SSCS.
**Does this PR introduce a breaking change?**
=> Add Panel Member roles

Jenkinsfile_CNP, Jenkinsfile_parameterized, build.gradle, docker-compose-dependencies.yml, docker-compose.yml, src/aat/java/uk/gov/hmcts/reform/coh/functional/bdd/steps/BaseSteps.java, src/aat/java/uk/gov/hmcts/reform/coh/functional/bdd/utils/Env.java, src/aat/java/uk/gov/hmcts/reform/coh/functional/bdd/utils/IdamHelper.java, src/aat/java/uk/gov/hmcts/reform/coh/functional/bdd/utils/S2sHelper.java, src/aat/java/uk/gov/hmcts/reform/coh/functional/bdd/utils/TestUtil.java, src/aat/resources/application.yaml
=> Checkpoint check in. Idam and S2S now working using OAuth

build.gradle
=> [PREVIEW] Sidam refusing to accept tokens that work in Tidam

build.gradle
Reverts hmcts/rpa-coh-continuous-online-resolution#280
=> Revert "[PREVIEW] Sidam refusing to accept tokens that work in Tidam"

build.gradle
=> Sidam refusing to accept tokens that work in Tidam

infrastructure/aat.tfvars, infrastructure/saat.tfvars, infrastructure/variables.tf
=> Point to Sidam

build.gradle, dependency-check-suppressions.xml
=> CVE complaint

src/main/java/uk/gov/hmcts/reform/coh/controller/AnswerController.java, src/test/java/uk/gov/hmcts/reform/coh/controller/AnswerControllerTest.java
=> Sonar Complaints

src/test/java/uk/gov/hmcts/reform/coh/controller/AnswerControllerTest.java
=> Test coverage for answer not found

src/main/java/uk/gov/hmcts/reform/coh/controller/AnswerController.java, src/test/java/uk/gov/hmcts/reform/coh/controller/LoggingAnswerUpdateErrorsTest.java
=> More sonar cube fixes

src/main/java/uk/gov/hmcts/reform/coh/controller/AnswerController.java, src/test/java/uk/gov/hmcts/reform/coh/controller/AnswerControllerTest.java
src/main/java/uk/gov/hmcts/reform/coh/controller/validators/AnswerValidator.java
**Does this PR introdusrc/main/java/uk/gov/hmcts/reform/coh/controller/validators/AnswerValidator.javace a breaking change?** (check one with "x")
```
[ ] Yes
[X ] No
```
=> More test coverage

src/main/java/uk/gov/hmcts/reform/coh/controller/AnswerController.java
=> Hopefully fix sonar complaint about XSS attack

src/main/java/uk/gov/hmcts/reform/coh/controller/AnswerController.java
=> Hopefully fix sonar complaints

src/main/java/uk/gov/hmcts/reform/coh/controller/AnswerController.java
=> Refactor this to sanitize user input and satisfy sonar

Dockerfile, Jenkinsfile_CNP
Set up Jenkins to update the docker image in the Azure Container Registry every time there's a PR merged into master
```
[ ] Yes
[x] No
```
=> update dockerfile and add enabledockerbuild

Dockerfile, Jenkinsfile_CNP, README.md, build.gradle, dependency-check-suppressions.xml, docker-compose-all.yml, docker-compose-dependencies.yml, docker-compose.yml, infrastructure/main.tf
https://tools.hmcts.net/jira/browse/EM-2112
update docker-compose files to use latest images with hmctspublic/hmctsprivate
```
[ ] Yes
[X] No
```
=> update docker-compose files to use latest images

infrastructure/main.tf
revert string interpolation changes
```
[ ] Yes
[X] No
```
=> revert string interpolation changes

infrastructure/aat.tfvars, infrastructure/main.tf, infrastructure/prod.tfvars, infrastructure/variables.tf, src/aat/java/uk/gov/hmcts/reform/coh/functional/bdd/runner/ContinuousOnlineHearingTests.java
=> add managed-id & disable F tests

charts/coh-cor/Chart.yaml, charts/coh-cor/values.aat.template.yaml
=> Disable aat pod DB
